const productsData = {
    "mor-utsav": {
        title: "Mor Utsav",
        artist: "Aanya Sharma",
        year: "2024",
        price: "₹8,500",
        category: "Madhubani",
        image: "kalacore abstract 2.jpg.jpeg",
        description: "A vibrant Madhubani composition featuring a regal peacock surrounded by blooming marigolds. Hand-painted with natural pigments following the traditional Mithila style passed down through generations.",
        medium: "Natural pigments on handmade paper",
        size: "16 × 24 inches",
        edition: "Original, 1 of 1"
    },
    "kashi-bhor": {
        title: "Kashi Bhor",
        artist: "Ishaan Mehta",
        year: "2023",
        price: "₹6,200",
        category: "Watercolor",
        image: "The silence of nature.jpg.jpeg",
        description: "Capturing the ethereal morning light at the ghats of Varanasi. This watercolor piece uses soft bleeds and delicate layers to evoke the spiritual calm of the Ganges at dawn.",
        medium: "Artist-grade watercolors on 300gsm cold-pressed paper",
        size: "12 × 18 inches",
        edition: "Original"
    },
    "vrindavan-leela": {
        title: "Vrindavan Leela",
        artist: "Radhika Joshi",
        year: "2024",
        price: "₹14,500",
        category: "Pichwai",
        image: "3.jpg",
        description: "A detailed Pichwai painting depicting Shrinathji amidst the lush groves of Vrindavan. Gold foil accents and stone pigments bring a celestial glow to this traditional masterpiece.",
        medium: "Stone pigments and gold foil on cotton fabric",
        size: "24 × 36 inches",
        edition: "Original"
    },
    "golden-horizon": {
        title: "Golden Horizon",
        artist: "Sumit Kumar",
        year: "2024",
        price: "₹15,500",
        category: "Oil on Canvas",
        image: "khat.jpg.jpeg",
        description: "An expressive oil painting exploring the interplay of light and texture. The 'Golden Horizon' symbolizes hope and the infinite possibilities of the creative mind.",
        medium: "Oil on stretched canvas",
        size: "20 × 20 inches (Square)",
        edition: "Original"
    },
    "divine-grace": {
        title: "Divine Grace",
        artist: "Meera Devi",
        year: "2024",
        price: "₹22,000",
        category: "Traditional Art",
        image: "divine-grace.png",
        description: "A magnificent depiction of celestial grace, inspired by ancient temple murals. Intricate patterns and a rich palette create a sense of timeless devotion.",
        medium: "Acrylic and mixed media",
        size: "30 × 40 inches",
        edition: "Original"
    },
    "natures-whisper": {
        title: "Nature's Whisper",
        artist: "Vikram Singh",
        year: "2023",
        price: "₹11,000",
        category: "Landscape",
        image: "1.jpeg",
        description: "A serene landscape that captures the quiet conversation between the wind and the trees. Perfect for bringing a touch of nature's peace into a modern living space.",
        medium: "Oil on canvas",
        size: "18 × 24 inches",
        edition: "Original"
    },
    "the-calm-soul": {
        title: "The Calm Soul",
        artist: "Ananya Roy",
        year: "2024",
        price: "₹9,500",
        category: "Portrait",
        image: "calm-soul.png",
        description: "A meditative portrait exploring inner peace and silence. The soft, blended tones create a soothing visual experience that resonates with the viewer's own sense of calm.",
        medium: "Oil on canvas",
        size: "24 × 24 inches",
        edition: "Original"
    },
    "ethereal-beauty": {
        title: "Ethereal Beauty",
        artist: "Rohan Gupta",
        year: "2024",
        price: "₹13,200",
        category: "Contemporary",
        image: "ethereal-beauty.png",
        description: "A stunning contemporary abstract painting that explores fluid, ethereal shapes in shades of deep blue and gold. It represents the beauty found in movement and light.",
        medium: "Mixed media on canvas",
        size: "24 × 30 inches",
        edition: "Original"
    },
    "mystic-forest": {
        title: "Mystic Forest",
        artist: "Karan Sharma",
        year: "2023",
        price: "₹18,900",
        category: "Acrylic",
        image: "2.jpg",
        description: "A journey into the deep, mysterious heart of an enchanted forest. Vibrant colors and bold strokes create a dynamic and immersive environment.",
        medium: "Acrylic on canvas",
        size: "30 × 30 inches",
        edition: "Original"
    },
    "royal-heritage": {
        title: "Royal Heritage",
        artist: "Rajesh Kumar",
        year: "2024",
        price: "₹35,000",
        category: "Classic",
        image: "4.HEIC.jpeg",
        description: "A classic painting celebrating the rich cultural heritage of India. Gold leaf work and traditional motifs make this a truly regal addition to any collection.",
        medium: "Oil and gold leaf on canvas",
        size: "36 × 48 inches",
        edition: "Original"
    },
    "abstract-mind": {
        title: "Abstract Mind",
        artist: "Pooja Verma",
        year: "2024",
        price: "₹7,800",
        category: "Modern Art",
        image: "2.jpg.jpeg",
        description: "An exploration of thoughts and emotions through abstract form. This piece encourages personal interpretation and deep reflection.",
        medium: "Acrylic and ink on paper",
        size: "16 × 16 inches",
        edition: "Original"
    },
    "village-life": {
        title: "Village Life",
        artist: "Suresh Patel",
        year: "2024",
        price: "₹5,500",
        category: "Folk Art",
        image: "3.jpg.jpeg",
        description: "A charming depiction of daily life in an Indian village. Vibrant colors and simple forms capture the joy and community of rural living.",
        medium: "Gouache on handmade paper",
        size: "11 × 15 inches",
        edition: "Original"
    }
};
